### ISSUE TITLE
Add Sorting Algorithms

### ISSUE THREAD

**Issue by exceptiionChan** [exceptiionChan/Data-Structures-and-Algorithms#5]

**Comment by baycak** [comment]
Hi, I'd would like to work on this issue

**Comment by lucasguiss** [comment]
hello, can i add bubblesort and linear search algorithms?

**Comment by AlecsisDuarte** [comment]
Hi @exceptiionChan,
I added a bubble sort algorithm in Dart, could you have a look?
#18

**Comment by AlecsisDuarte** [comment]
I also added it in Java flavor 👀
#19

**Comment by AlecsisDuarte** [comment]
Just an FYI - Hacktober fest is not seeing this PRs as valid Hacktober-fest PRs. 
If so, could you also add the `hacktoberfest-accepted` tag to the PR?

Thanks in advance!
